Shibu Mohapatra

Artificial intelligence

**Design and train the Hopfield net to map the input vector with the stored vector and correct them**

In [1]:
import numpy as np
import random
from random import shuffle

In [2]:
y = np.array([1,1,0,0,0,0])
print(y)

[1 1 0 0 0 0]


In [3]:
for i in range(6):
    y[i] = y[i]*2-1
print(y)

[ 1  1 -1 -1 -1 -1]


In [4]:
def create_W(x):
    w = np.zeros([len(x),len(x)])
    for i in range(len(x)):
        for j in range(i,len(x)):
                if i == j:
                    w[i,j] = 0
                else:
                    w[i,j] = x[i]*x[j]
                    w[j,i] = w[i,j]
    return w

w = create_W(y)
print(w)

[[ 0.  1. -1. -1. -1. -1.]
 [ 1.  0. -1. -1. -1. -1.]
 [-1. -1.  0.  1.  1.  1.]
 [-1. -1.  1.  0.  1.  1.]
 [-1. -1.  1.  1.  0.  1.]
 [-1. -1.  1.  1.  1.  0.]]


In [5]:
y_vec = np.array([1,1,0,0,1,1])

for i in range(6):
    y_vec[i] = y_vec[i]*2-1
    
print(y_vec)

[ 1  1 -1 -1  1  1]


In [6]:
def update(w,y_vec):
    i = np.array([0,1,2,3,4,5])
    shuffle(i)
    for j in i :
        u = np.dot(w[j][:],y_vec)

        if u > 0:
            y_vec[j] = 1
        elif u < 0:
            y_vec[j] = -1

    return y_vec
    
print(y_vec)

[ 1  1 -1 -1  1  1]


In [7]:
i=0
while i<1 :
    print(y_vec)
    ycheck = y_vec
    update(w,y_vec)
    print(" --> ",y_vec)
    k=0
    for j in range(6) :
        if ycheck[j] == y_vec[j] :
            k = k+1
    if(k==6):
        i=1
        
print("final stable point : ",y_vec)   

[ 1  1 -1 -1  1  1]
 -->  [ 1  1 -1 -1 -1 -1]
final stable point :  [ 1  1 -1 -1 -1 -1]
